# Generated by Django 6.0.5 on 2026-05-16 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('repo_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('readme', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('open_issues', models.IntegerField(default=0)),
                ('contributors_count', models.IntegerField(default=0)),
                ('activity_score', models.FloatField(default=0)),
                ('beginner_score', models.FloatField(default=0)),
                ('doc_score', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('last_commit', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, null=True)),
                ('issue_url', models.URLField()),
                ('difficulty_score', models.FloatField(default=0)),
                ('is_good_first_issue', models.BooleanField(default=False)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='repositories.repository')),
            ],
        ),
    ]
