# Generated by Django 6.0.5 on 2026-05-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='maintenance_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
    ]
