# Generated by Django 6.0.5 on 2026-05-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_repository_maintenance_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
