# Generated by Django 6.0.5 on 2026-05-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_repository_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='github_issue_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='issue',
            name='state',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('repository', 'github_issue_number')},
        ),
    ]
