# Generated by Django 6.0.5 on 2026-05-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_repositorywatch_issuenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ai_learning_guide',
            field=models.TextField(blank=True, null=True),
        ),
    ]
